[package]
name = "LianT"
version = "0.1.0"
edition = "2021"
description = "LianT — COSMIC-style (Rust + Slint)"
license = "Apache-2.0"

[dependencies]
slint = "1.9"

[build-dependencies]
slint-build = "1.9"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = 2