name = "LianT"
product-name = "LianT"
identifier = "com.bailensn.liant"

version = "0.0.0"

out-dir = "../release"
formats = ["nsis"]

icons = ["../resources/windows/LianT.ico"]

[[binaries]]
path = "liant"
main = true

[nsis]
installer-icon = "../resources/windows/LianT.ico"
install-mode = "currentUser"