name = "LianT"
product-name = "LianT"
identifier = "com.bailensn.liant"

version = "1.0.0"

out-dir = "../release"
formats = ["nsis"]

binaries = ["liant"]

icons = ["../resources/windows/LianT.ico"]

[nsis]
installer-icon = "../resources/windows/LianT.ico"
install-mode = "currentUser"