name: Build Manager Desktop

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.0.0'

      windows:
        type: boolean
        default: false

      darwin_arm64:
        type: boolean
        default: false

      darwin_amd64:
        type: boolean
        default: false

      linux_amd64:
        type: boolean
        default: false

      linux_arm64:
        type: boolean
        default: false


env:
  GRADLE_OPTS: -Dorg.gradle.java.installations.auto-download=false


jobs:

  windows-amd64:
    if: ${{ inputs.windows }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v6

      - name: Pin Gradle toolchain
        run: echo "toolchainVersion=21" > manager/desktop/gradle/gradle-daemon-jvm.properties

      - name: Build bare app
        working-directory: manager/desktop
        run: ./gradlew :desktopApp:createDistributable --no-daemon

      - name: UPX compress
        working-directory: manager/desktop
        run: |
          Invoke-WebRequest `
            -Uri "https://github.com/upx/upx/releases/download/v5.2.0/upx-5.2.0-win64.zip" `
            -OutFile upx.zip

          7z x -y upx.zip

          Get-ChildItem "desktopApp/build/compose/binaries/main/app" -Filter *.exe -Recurse | ForEach-Object {
            ./upx-5.2.0-win64/upx.exe -9 $_.FullName
          }

          Get-ChildItem "desktopApp/build/compose/binaries/main/app" -Filter *.dll -Recurse | ForEach-Object {
            ./upx-5.2.0-win64/upx.exe -9 $_.FullName
          }

      - name: Build installer
        run: |
          choco install innosetup -y --no-progress

          iscc manager/desktop/installer.iss

          Move-Item `
            manager/desktop/Output/LianT.exe `
            LianT_${{ inputs.version }}_amd64.exe

      - uses: actions/upload-artifact@v7
        with:
          name: LianT-Windows-amd64
          path: LianT_${{ inputs.version }}_amd64.exe

  darwin-arm64:
    if: ${{ inputs.darwin_arm64 }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          architecture: arm64

      - uses: gradle/actions/setup-gradle@v6

      - name: Pin Gradle toolchain
        run: echo "toolchainVersion=21" > manager/desktop/gradle/gradle-daemon-jvm.properties

      - name: Build bare app
        working-directory: manager/desktop
        run: ./gradlew :desktopApp:createDistributable --no-daemon

      - name: Make app bundle
        run: |
          APP="manager/desktop/desktopApp/build/compose/binaries/main/app"

          mkdir -p LianT.app/Contents/MacOS
          mkdir -p LianT.app/Contents/Resources

          cp -r "$APP"/* LianT.app/Contents/MacOS/

          cp manager/resources/darwin/LianT.icns \
            LianT.app/Contents/Resources/

          cat << EOF > LianT.app/Contents/Info.plist
          <?xml version="1.0"?>
          <plist version="1.0">
          <dict>
            <key>CFBundleName</key>
            <string>LianT</string>

            <key>CFBundleExecutable</key>
            <string>LianT</string>

            <key>CFBundleIdentifier</key>
            <string>com.bailensn.liant</string>

            <key>CFBundleVersion</key>
            <string>${{ inputs.version }}</string>

            <key>CFBundleIconFile</key>
            <string>LianT.icns</string>

            <key>CFBundlePackageType</key>
            <string>APPL</string>
          </dict>
          </plist>
          EOF

      - name: Create dmg
        run: |
          hdiutil create \
            -volname LianT \
            -srcfolder LianT.app \
            -ov \
            -format UDZO \
            LianT_${{ inputs.version }}_arm64.dmg

      - uses: actions/upload-artifact@v7
        with:
          name: LianT-Darwin-arm64
          path: LianT_${{ inputs.version }}_arm64.dmg

  darwin-amd64:
    if: ${{ inputs.darwin_amd64 }}
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          architecture: x64

      - uses: gradle/actions/setup-gradle@v6

      - name: Pin Gradle toolchain
        run: echo "toolchainVersion=21" > manager/desktop/gradle/gradle-daemon-jvm.properties

      - name: Build bare app
        working-directory: manager/desktop
        run: ./gradlew :desktopApp:createDistributable --no-daemon

      - name: Make app bundle
        run: |
          APP="manager/desktop/desktopApp/build/compose/binaries/main/app"

          mkdir -p LianT.app/Contents/MacOS
          mkdir -p LianT.app/Contents/Resources

          cp -r "$APP"/* LianT.app/Contents/MacOS/

          cp manager/resources/darwin/LianT.icns \
            LianT.app/Contents/Resources/

          cat << EOF > LianT.app/Contents/Info.plist
          <?xml version="1.0"?>
          <plist version="1.0">
          <dict>
            <key>CFBundleName</key>
            <string>LianT</string>

            <key>CFBundleExecutable</key>
            <string>LianT</string>

            <key>CFBundleIdentifier</key>
            <string>com.bailensn.liant</string>

            <key>CFBundleVersion</key>
            <string>${{ inputs.version }}</string>

            <key>CFBundleIconFile</key>
            <string>LianT.icns</string>

            <key>CFBundlePackageType</key>
            <string>APPL</string>
          </dict>
          </plist>
          EOF

      - name: Create dmg
        run: |
          hdiutil create \
            -volname LianT \
            -srcfolder LianT.app \
            -ov \
            -format UDZO \
            LianT_${{ inputs.version }}_amd64.dmg

      - uses: actions/upload-artifact@v7
        with:
          name: LianT-Darwin-amd64
          path: LianT_${{ inputs.version }}_amd64.dmg

  linux-amd64:
    if: ${{ inputs.linux_amd64 }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v6

      - name: Install build tools
        run: |
          sudo sed -i 's|azure.archive.ubuntu.com|archive.archive.ubuntu.com|g; /packages.microsoft.com/d' /etc/apt/sources.list

          sudo apt-get update -y

          sudo apt-get install -y fakeroot rpm

      - name: Pin Gradle toolchain
        run: echo "toolchainVersion=21" > manager/desktop/gradle/gradle-daemon-jvm.properties

      - name: Build bare app
        working-directory: manager/desktop
        run: ./gradlew :desktopApp:createDistributable --no-daemon

      - name: Package deb
        run: |
          APP="manager/desktop/desktopApp/build/compose/binaries/main/app"
          PKG="pkg-deb"

          rm -rf "$PKG"

          mkdir -p "$PKG"/DEBIAN
          mkdir -p "$PKG"/opt/LianT
          mkdir -p "$PKG"/usr/bin
          mkdir -p "$PKG"/usr/share/applications

          for d in manager/resources/linux/*; do
            sz=$(basename "$d")

            [[ "$sz" =~ ^[0-9]+$ ]] || continue

            mkdir -p "$PKG"/usr/share/icons/hicolor/${sz}x${sz}/apps

            cp "$d"/LianT.png \
              "$PKG"/usr/share/icons/hicolor/${sz}x${sz}/apps/
          done

          cp -r "$APP"/* "$PKG"/opt/LianT/

          ln -s /opt/LianT/LianT/bin/LianT \
            "$PKG"/usr/bin/LianT

          sed \
            "s|^Exec=.*|Exec=/usr/bin/LianT|; s|^Icon=.*|Icon=LianT|" \
            manager/resources/linux/LianT.desktop \
            > "$PKG"/usr/share/applications/LianT.desktop

          cat << EOF > "$PKG"/DEBIAN/control
          Package: liant
          Version: ${{ inputs.version }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: LianT Team <bailensnn@gmail.com>
          Description: LianT Manager Desktop
           Cross-platform manager tool for LianT service.
          EOF

          fakeroot dpkg-deb \
            --build \
            "$PKG" \
            LianT_${{ inputs.version }}_amd64.deb

      - name: Package rpm
        run: |
          APP="manager/desktop/desktopApp/build/compose/binaries/main/app"

          mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS}

          mkdir -p rpmbuild/SOURCES/LianT

          cp -r "$APP"/* rpmbuild/SOURCES/LianT/

          cat << EOF > rpmbuild/SPECS/liant.spec
          Name: liant
          Version: ${{ inputs.version }}
          Release: 1
          Summary: LianT Manager Desktop
          License: GPL
          BuildArch: x86_64

          %description
          Cross-platform manager tool for LianT service.

          %install
          mkdir -p %{buildroot}/opt/LianT
          mkdir -p %{buildroot}/usr/bin

          cp -r %{_sourcedir}/LianT/* %{buildroot}/opt/LianT/

          ln -s /opt/LianT/LianT/bin/LianT %{buildroot}/usr/bin/LianT

          %files
          /opt/LianT
          /usr/bin/LianT
          EOF

          rpmbuild \
            --define "_topdir $(pwd)/rpmbuild" \
            -bb rpmbuild/SPECS/liant.spec

          cp rpmbuild/RPMS/x86_64/*.rpm \
            LianT_${{ inputs.version }}_amd64.rpm

      - uses: actions/upload-artifact@v7
        with:
          name: LianT-Linux-amd64
          path: |
            LianT_${{ inputs.version }}_amd64.deb
            LianT_${{ inputs.version }}_amd64.rpm


  linux-arm64:
    if: ${{ inputs.linux_arm64 }}
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v6

      - name: Install build tools
        run: |
          sudo sed -i 's|azure.archive.ubuntu.com|archive.archive.ubuntu.com|g; /packages.microsoft.com/d' /etc/apt/sources.list

          sudo apt-get update -y

          sudo apt-get install -y fakeroot rpm

      - name: Pin Gradle toolchain
        run: echo "toolchainVersion=21" > manager/desktop/gradle/gradle-daemon-jvm.properties

      - name: Build bare app
        working-directory: manager/desktop
        run: ./gradlew :desktopApp:createDistributable --no-daemon

      - name: Package deb
        run: |
          APP="manager/desktop/desktopApp/build/compose/binaries/main/app"
          PKG="pkg-deb"

          rm -rf "$PKG"

          mkdir -p "$PKG"/DEBIAN
          mkdir -p "$PKG"/opt/LianT
          mkdir -p "$PKG"/usr/bin
          mkdir -p "$PKG"/usr/share/applications

          for d in manager/resources/linux/*; do
            sz=$(basename "$d")

            [[ "$sz" =~ ^[0-9]+$ ]] || continue

            mkdir -p "$PKG"/usr/share/icons/hicolor/${sz}x${sz}/apps

            cp "$d"/LianT.png \
              "$PKG"/usr/share/icons/hicolor/${sz}x${sz}/apps/
          done

          cp -r "$APP"/* "$PKG"/opt/LianT/

          ln -s /opt/LianT/LianT/bin/LianT \
            "$PKG"/usr/bin/LianT

          sed \
            "s|^Exec=.*|Exec=/usr/bin/LianT|; s|^Icon=.*|Icon=LianT|" \
            manager/resources/linux/LianT.desktop \
            > "$PKG"/usr/share/applications/LianT.desktop

          cat << EOF > "$PKG"/DEBIAN/control
          Package: liant
          Version: ${{ inputs.version }}
          Section: utils
          Priority: optional
          Architecture: arm64
          Maintainer: LianT Team <bailensnn@gmail.com>
          Description: LianT Manager Desktop
           Cross-platform manager tool for LianT service.
          EOF

          fakeroot dpkg-deb \
            --build \
            "$PKG" \
            LianT_${{ inputs.version }}_arm64.deb

      - name: Package rpm
        run: |
          APP="manager/desktop/desktopApp/build/compose/binaries/main/app"

          mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS}

          mkdir -p rpmbuild/SOURCES/LianT

          cp -r "$APP"/* rpmbuild/SOURCES/LianT/

          cat << EOF > rpmbuild/SPECS/liant.spec
          Name: liant
          Version: ${{ inputs.version }}
          Release: 1
          Summary: LianT Manager Desktop
          License: GPL
          BuildArch: aarch64

          %description
          Cross-platform manager tool for LianT service.

          %install
          mkdir -p %{buildroot}/opt/LianT
          mkdir -p %{buildroot}/usr/bin

          cp -r %{_sourcedir}/LianT/* %{buildroot}/opt/LianT/

          ln -s /opt/LianT/LianT/bin/LianT %{buildroot}/usr/bin/LianT

          %files
          /opt/LianT
          /usr/bin/LianT
          EOF

          rpmbuild \
            --define "_topdir $(pwd)/rpmbuild" \
            -bb rpmbuild/SPECS/liant.spec

          cp rpmbuild/RPMS/aarch64/*.rpm \
            LianT_${{ inputs.version }}_arm64.rpm

      - uses: actions/upload-artifact@v7
        with:
          name: LianT-Linux-arm64
          path: |
            LianT_${{ inputs.version }}_arm64.deb
            LianT_${{ inputs.version }}_arm64.rpm